### ISSUE TITLE
Cannot find class SubmitPartial, PoolInfo from chia.protocols.pool_protocol

### ISSUE THREAD

**Issue by truongthihuonggiang** [Chia-Network/pool-reference#8] opened 2021-05-20 21:57 UTC
I have look at file pool_protocol.py, it doesn't have these class, Submit Partial and PoolInfo. Any help?

**Comment by Gerraweb** [comment] 2021-05-21 09:47
Duplicate of #1

**Comment by mariano54** [comment] 2021-05-25 12:30
These are in chia-blockchain. This has not been released yet so we're not providing customer support.

**Closed by mariano54** 2021-05-25 12:30 UTC
