### ISSUE TITLE
Can't select amount higher than our spendable balance

### ISSUE THREAD

**Issue by chenhonghe** [Chia-Network/pool-reference#62] opened 2021-06-10 13:33 UTC
How to solve this error?

```
INFO:root:Submitting a payment: [{'puzzle_hash': <bytes32: 1b25b30ce5c5cc0a9c7329a44fdd2332bd9a850c8baf276c5de74613c5a05935>, 'amount': 10000000000}, {'puzzle_hash': <bytes32: 681ffb60270df72fbe7f068cad2452b8e52013a22afb483712785585e06a9ffe>, 'amount': 990000000000.0001}]
ERROR:root:Error making payment: {'error': "Can't select amount higher than our spendable balance.  Amount: 1000020000000, spendable:  1000000000000", 'success': False}
```

**Comment by mariano54** [comment] 2021-06-10 21:55
Are you using the latest code? I think the new code uses 0 fee so there is always enough funds.

**Comment by chenhonghe** [comment] 2021-06-11 02:31
Error running the latest code.

`
INFO:root:Obtaining balance: {'confirmed_wallet_balance': 213571045, 'max_send_amount': 213571045, 'pending_change': 0, 'pending_coin_removal_count': 0, 'spendable_balance': 213571045, 'unconfirmed_wallet_balance': 213571045, 'unspent_coin_count': 1, 'wallet_id': 1}
INFO:root:Starting to create payment
WARNING:root:Waiting for wallet sync
INFO:root:Scanning for block rewards from 1000 to 179539. Found: 19
ERROR:root:Unexpected error in collect_pool_rewards_loop: Length of bytes object not equal to G1Element::SIZE Traceback (most recent call last):
  File "/data/pool-reference/pool/pool.py", line 256, in collect_pool_rewards_loop
    set([ph for ph in ph_to_amounts.keys()])
  File "/data/pool-reference/pool/store.py", line 159, in get_farmer_records_for_p2_singleton_phs
    return [self._row_to_farmer_record(row) for row in rows]
  File "/data/pool-reference/pool/store.py", line 159, in <listcomp>
    return [self._row_to_farmer_record(row) for row in rows]
  File "/data/pool-reference/pool/store.py", line 76, in _row_to_farmer_record
    G1Element.from_bytes(bytes.fromhex(str(row[2]))),
ValueError: Length of bytes object not equal to G1Element::SIZE

INFO:root:No funds to distribute.
WARNING:__main__:Error while handling message: Traceback (most recent call last):
  File "pool/pool_server.py", line 45, in inner
    res_object = await f(request)
  File "pool/pool_server.py", line 87, in submit_partial
    farmer_record: Optional[FarmerRecord] = await self.pool.store.get_farmer_record(partial.payload.launcher_id)
  File "/data/pool-reference/pool/store.py", line 114, in get_farmer_record
    return self._row_to_farmer_record(row)
  File "/data/pool-reference/pool/store.py", line 76, in _row_to_farmer_record
    G1Element.from_bytes(bytes.fromhex(str(row[2]))),
ValueError: Length of bytes object not equal to G1Element::SIZE

WARNING:__main__:Error while handling message: Traceback (most recent call last):
  File "pool/pool_server.py", line 45, in inner
    res_object = await f(request)
  File "pool/pool_server.py", line 87, in submit_partial
    farmer_record: Optional[FarmerRecord] = await self.pool.store.get_farmer_record(partial.payload.launcher_id)
  File "/data/pool-reference/pool/store.py", line 114, in get_farmer_record
    return self._row_to_farmer_record(row)
  File "/data/pool-reference/pool/store.py", line 76, in _row_to_farmer_record
    G1Element.from_bytes(bytes.fromhex(row[2])),
ValueError: Length of bytes object not equal to G1Element::SIZE

INFO:root:Logging in: {'fingerprint': 814018973, 'success': True}
INFO:root:Obtaining balance: {'confirmed_wallet_balance': 213571045, 'max_send_amount': 213571045, 'pending_change': 0, 'pending_coin_removal_count': 0, 'spendable_balance': 213571045, 'unconfirmed_wallet_balance': 213571045, 'unspent_coin_count': 1, 'wallet_id': 1}
INFO:root:Starting to create payment
WARNING:root:Waiting for wallet sync
INFO:root:Scanning for block rewards from 1000 to 179550. Found: 19
ERROR:root:Unexpected error in collect_pool_rewards_loop: fromhex() argument must be str, not int Traceback (most recent call last):
  File "/data/pool-reference/pool/pool.py", line 256, in collect_pool_rewards_loop
    set([ph for ph in ph_to_amounts.keys()])
  File "/data/pool-reference/pool/store.py", line 159, in get_farmer_records_for_p2_singleton_phs
    return [self._row_to_farmer_record(row) for row in rows]
  File "/data/pool-reference/pool/store.py", line 159, in <listcomp>
    return [self._row_to_farmer_record(row) for row in rows]
  File "/data/pool-reference/pool/store.py", line 76, in _row_to_farmer_record
    G1Element.from_bytes(bytes.fromhex(row[2])),
TypeError: fromhex() argument must be str, not int

INFO:root:No funds to distribute.
INFO:root:Starting to create payment
INFO:root:No funds to distribute.
INFO:root:Starting to create payment
INFO:root:No funds to distribute.
INFO:root:Starting to create payment
INFO:root:No funds to distribute.
INFO:root:Starting to create payment
INFO:root:No funds to distribute.
INFO:root:Scanning for block rewards from 1000 to 179581. Found: 19
ERROR:root:Unexpected error in collect_pool_rewards_loop: fromhex() argument must be str, not int Traceback (most recent call last):
  File "/data/pool-reference/pool/pool.py", line 256, in collect_pool_rewards_loop
    set([ph for ph in ph_to_amounts.keys()])
  File "/data/pool-reference/pool/store.py", line 159, in get_farmer_records_for_p2_singleton_phs
    return [self._row_to_farmer_record(row) for row in rows]
  File "/data/pool-reference/pool/store.py", line 159, in <listcomp>
    return [self._row_to_farmer_record(row) for row in rows]
  File "/data/pool-reference/pool/store.py", line 76, in _row_to_farmer_record
    G1Element.from_bytes(bytes.fromhex(row[2])),
TypeError: fromhex() argument must be str, not int
`

**Comment by tmoore22** [comment] 2021-06-14 00:29
duplicate of: https://github.com/Chia-Network/pool-reference/issues/63

this should be solved in latest pull now

**Closed** 2021-06-14 00:43 UTC
