### ISSUE TITLE
No points for any farmer.

### ISSUE THREAD

**Issue by jianghushinian** [Chia-Network/pool-reference#190] opened 2021-07-20 02:23 UTC
When I execute `chia plots create -c xxx -t xxx -d xxx` successfully, I don't get the `INFO:root:Returning` log, and there is no keyword `Returning` in the source code. Is it because the code is updated but the document is not updated? In addition, the log of the pool still shows the reason for `No points for any farmer. Waiting 600` and when will there be `points`.

[calculate a farmer's netspace](https://github.com/Chia-Network/chia-blockchain/wiki/Pooling-FAQ#how-does-one-calculate-a-farmers-netspace), needs points.

**Comment by zheng9980419** [comment] 2021-07-20 03:16
加个vx  9980419,我也是这个问题交流一下

**Comment by mariano54** [comment] 2021-07-21 02:02
You need to run a farmer and connect it to the pool. Check the User guide for how to use pooling. 
Closing since this is not a bug.

**Closed by mariano54** 2021-07-21 02:02 UTC
